/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package de.serverfrog.frogchat.gui.services;
	
import javax.inject.Inject;
import javax.inject.Named;
import org.granite.client.messaging.RemoteAlias;
import org.granite.client.tide.server.ServerSession;

@Named
@RemoteAlias("de.serverfrog.frogchat.services.UserService")
public class UserService extends UserServiceBase {
	
	@Inject
	public UserService(ServerSession serverSession) {
    	super(serverSession);
    }
}
