/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package de.serverfrog.frogchat.gui.entities;

import org.granite.client.messaging.RemoteAlias;
import org.granite.messaging.annotations.Serialized;

@Serialized
@RemoteAlias("de.serverfrog.frogchat.entities.UserList")
public class UserList extends UserListBase {

    private static final long serialVersionUID = 1L;
}